services:
    alex_dpy_acl.acl_checker.collector:
        class: AlexDpy\AclBundle\DataCollector\Collector\AclCheckerCollector
        public: false
        decorates: alex_dpy_acl.acl_checker
        arguments:
            - @alex_dpy_acl.acl_checker.collector.inner
            - @debug.stopwatch

    alex_dpy_acl.acl_manager.collector:
        class: AlexDpy\AclBundle\DataCollector\Collector\AclManagerCollector
        public: false
        decorates: alex_dpy_acl.acl_manager
        arguments:
            - @alex_dpy_acl.acl_manager.collector.inner
            - @debug.stopwatch

    alex_dpy_acl.acl_filter.collector:
        class: AlexDpy\AclBundle\DataCollector\Collector\AclFilterCollector
        public: false
        decorates: alex_dpy_acl.acl_filter
        arguments:
            - @alex_dpy_acl.acl_filter.collector.inner
            - @debug.stopwatch

    alex_dpy_acl.acl_data_collector:
        class: AlexDpy\AclBundle\DataCollector\AclDataCollector
        arguments:
            - @alex_dpy_acl.acl_checker.collector
            - @alex_dpy_acl.acl_manager.collector
            - @alex_dpy_acl.acl_filter.collector
        tags:
            - { name: data_collector, template: "AlexDpyAclBundle:Profiler:acl", id: acl }
