parameters:
    acl_tables:
        class: %security.acl.dbal.class_table_name%
        entry: %security.acl.dbal.entry_table_name%
        oid: %security.acl.dbal.oid_table_name%
        oid_ancestor: %security.acl.dbal.oid_ancestors_table_name%
        sid: %security.acl.dbal.sid_table_name%

services:
    alex_dpy_acl.acl_identifier:
        class: AlexDpy\AclBundle\Manager\AclIdentifier
        arguments:
            - @security.context
            - @security.acl.provider
            - @security.acl.dbal.connection
            - %acl_tables%

    alex_dpy_acl.acl_manager:
        class: AlexDpy\AclBundle\Manager\AclManager
        arguments:
            - @alex_dpy_acl.acl_identifier
            - @security.acl.provider
        calls:
            - [ setPermissionMap, [ @alex_dpy_acl.permission_map ] ]

    alex_dpy_acl.acl_checker:
        class: AlexDpy\AclBundle\Manager\AclChecker
        arguments:
            - @alex_dpy_acl.acl_identifier
            - @security.context
            - @security.access.decision_manager

    alex_dpy_acl.acl_filter:
        class: AlexDpy\AclBundle\Manager\AclFilter
        arguments:
            - @alex_dpy_acl.acl_identifier
            - @security.role_hierarchy
            - @security.context
            - %acl_tables%
        calls:
            - [ setPermissionMap, [ @alex_dpy_acl.permission_map ] ]
