services:
    alex_dpy_acl.acl_manager:
        class: AlexDpy\AclBundle\Manager\AclManager
        arguments:
            - @alex_dpy_acl.permission_map
            - @security.authorization_checker
            - @security.token_storage
            - @security.acl.provider
            - @security.access.decision_manager

    alex_dpy_acl.twig.security_extension:
        class: AlexDpy\AclBundle\Twig\SecurityExtension
        arguments: [ @alex_dpy_acl.acl_manager ]
        tags:
            - { name: twig.extension }
