services:
    alex_dpy_acl.acl_identifier:
        class: AlexDpy\AclBundle\Manager\AclIdentifier
        arguments:
            - @security.token_storage

    alex_dpy_acl.acl_manager:
        class: AlexDpy\AclBundle\Manager\AclManager
        arguments:
            - @alex_dpy_acl.acl_identifier
            - @security.acl.provider
        calls:
            - [ setPermissionMap, [ @alex_dpy_acl.permission_map ] ]

    alex_dpy_acl.acl_checker:
        class: AlexDpy\AclBundle\Manager\AclChecker
        arguments:
            - @alex_dpy_acl.acl_identifier
            - @security.authorization_checker
            - @security.access.decision_manager

    alex_dpy_acl.acl_filter:
        class: AlexDpy\AclBundle\Manager\AclFilter
        arguments:
            - @alex_dpy_acl.acl_identifier
            - @security.role_hierarchy
            - @security.token_storage
        calls:
            - [ setPermissionMap, [ @alex_dpy_acl.permission_map ] ]
